### ISSUE TITLE
Script error: Exec. of native 00..406b4b20

### ISSUE THREAD

**Issue by atarifeels** [qbcore-redm-framework/qbr-multicharacter#10]
![image](https://user-images.githubusercontent.com/51056927/161170458-5324449d-de25-4bfe-acd7-7ca111016bdd.png)
Happens as soon as character is created in the customization menu

**Comment by AndrewR3K** [comment]
I am also running into this exact issue with my newly created RedM server. 

**Issue:**

When  I connect to the server and create a new Character, I get the below errors in the backend server logs. However I do not see any errors in the F8 menu, but I cannot move the newly created character or use any keys other than the F8 menu.

**Error:**

`[script:qbr-multichar] > ref (@qbr-multicharacter/server/main.lua:115) [script:qbr-multichar] > Query.onResult (@oxmysql/dist/build.js:21711) [script:qbr-multichar] > <unknown> (@oxmysql/dist/build.js:11918) [script:qbr-multichar] > processTicksAndRejections (node:internal/process/task_queues:78) [ script:oxmysql] Uncaught Error: Error in nested ref call. [ script:oxmysql] citizen:/scripting/v8/main.js(85,12): [ script:oxmysql] citizen:/scripting/v8/main.js(23,12): __cfx_wrap_83 [ script:oxmysql] citizen:/scripting/v8/main.js(29,16): [ script:oxmysql] citizen:/scripting/v8/main.js(81,11): [ script:oxmysql] @oxmysql/dist/build.js(21711,7): [ script:oxmysql] @oxmysql/dist/build.js(11918,20): [ script:oxmysql] node:internal/process/task_queues(78,11): processTicksAndRejections [ script:oxmysql] [ script:oxmysql] Error: Error in nested ref call. [ script:qbr-core] [qbr-core:LOG] Testing Martial PLAYER SAVED! [ c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null. [script:qbr-multichar] SCRIPT ERROR: Execution of native 00000000406b4b20 in script host failed: Argument at index 0 was null.`

Thanks in advance for any help/advice!

**Comment by AndrewR3K** [comment]
Some more info from my little bit of digging around. (Sorry in advance for any lack of knowledge, super new here)

[@qbr-multicharacter/server/main.lua:115](https://github.com/qbcore-redm-framework/qbr-multicharacter/blob/main/server/main.lua#L113-L119)

Looks like this is erroring out on the `json.decode` function of the object return from a query of the 'playerskins' table. Digging around my DB, I'm noticing that my `playerskins` table is empty, which would make sense as to why the json.decode might break.

I'm guessing wherever the player is being created, the skin (maybe outfit as well) is not being populated correctly into the DB. 

Hopefully, this info helps out a bit.

**Comment by atarifeels** [comment]
> Digging around my DB, I'm noticing that my `playerskins` table is empty, which would make sense as to why the json.decode might break.
> 
> I'm guessing wherever the player is being created, the skin (maybe outfit as well) is not being populated correctly into the DB.
> 
> Hopefully, this info helps out a bit.

Yes, that is where the problem ended. The problem started in creating the character, we couldn't make "skin/character visual" _(where data are stored in `playerskins` as you mentioned correctly)_, because of the native problem I fixed in PR #11. Now it runs smoothly and we can create a skin for the player.

**Comment by atarifeels** [comment]
I closed this issue but forgot it would close PR as well, sorry for spam!
