### ISSUE TITLE
SCRIPT ERROR: @qbr-multicharacter/server/main.lua:116: attempt to index a nil value (field 'integer index')

### ISSUE THREAD

**Issue by smokezG** [qbcore-redm-framework/qbr-multicharacter#20]
![image](https://github.com/qbcore-redm-framework/qbr-multicharacter/assets/147995290/fd8a5c20-deda-4fc3-bbf4-c3c88b233e19)

**Comment by smokezG** [comment]
It doesn't let me do anything in the menu

**Comment by smokezG** [comment]
Also it doesn't save the outfits

**Comment by IDKFORCE** [comment]
thanks for reporting this issue our dev team is looking for the issue!!
